plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'

    // Analizar Composables
    id 'com.github.skydoves.compose.stability.analyzer'

    // Composable
    id 'org.jetbrains.kotlin.plugin.compose'

    // Necesario para Dagger Hilt
    id 'kotlin-kapt' // A traves de las anotaciones genera el código por atrás.
    id 'com.google.devtools.ksp'
    id 'com.google.dagger.hilt.android'

    // Serializable
    id 'org.jetbrains.kotlin.plugin.serialization'

    // @Parcelize
    id 'kotlin-parcelize'

    // Kover
    id "org.jetbrains.kotlinx.kover"

    // 🔑 CLAVE: Aplicar el plugin aquí.
    //id 'org.jetbrains.kotlinx.kover'
    id("io.github.takahirom.roborazzi")
}

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file("key.properties")

if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    compileSdk 36
    namespace 'com.jonathanev.review'

    defaultConfig {
        applicationId "com.jonathanev.review"
        minSdk 26
        targetSdk 35
        versionCode 20
        versionName "2.11"

        // Con TestRunner personalizado, falta investigar mas este punto
        //testInstrumentationRunner "com.jonathanev.review.CustomTestRunner"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            if (keystoreProperties != null && keystoreProperties['storeFile'] != null) {
                // LINEAS DE DIAGNÓSTICO:
                println "🔍 [DIAGNOSTIC] storeFile leído: ${keystoreProperties['storeFile']}"
                println "🔍 [DIAGNOSTIC] Largo de storePassword: ${keystoreProperties['storePassword']?.length()}"
                println "🔍 [DIAGNOSTIC] keyAlias leído: ${keystoreProperties['keyAlias']}"
                println "🔍 [DIAGNOSTIC] Largo de keyPassword: ${keystoreProperties['keyPassword']?.length()}"

                storeFile file(keystoreProperties['storeFile'])
                storePassword keystoreProperties['storePassword']
                keyAlias keystoreProperties['keyAlias']
                keyPassword keystoreProperties['keyPassword']
            } else {
                println "🔍 [DIAGNOSTIC] El if falló, las propiedades son nulas."
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled true // Optimisation, reduction, ofuscation
            shrinkResources true // Reduction about resources (Image)
            debuggable false
            resValue("string", "nameApp", "Review")
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release

            ndk {
                debugSymbolLevel 'FULL'
            }
        }

        debug {
            minifyEnabled false // Optimisation, reduction, ofuscation
            shrinkResources false // Reduction about resources (Image)
            debuggable true
            resValue("string", "nameApp", "Review [DEBUG]")

            enableAndroidTestCoverage true
            testCoverageEnabled true // Habilita cobertura en AndroidTest
            enableUnitTestCoverage true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlin {
        jvmToolchain {
            languageVersion.set(JavaLanguageVersion.of(17))
        }
    }

    buildFeatures {
        compose true
        viewBinding true
        buildConfig true
    }

    testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }
}

dependencies {
    implementation platform('androidx.compose:compose-bom:2024.08.00')

    implementation 'androidx.compose.ui:ui'
    implementation 'androidx.compose.ui:ui-graphics'
    implementation 'androidx.compose.material3:material3'
    implementation 'androidx.activity:activity-compose'
    implementation 'androidx.navigation:navigation-compose'
    implementation 'androidx.compose.ui:ui-tooling-preview'
    debugImplementation 'androidx.compose.ui:ui-tooling'

    implementation 'androidx.appcompat:appcompat:1.4.1'
    implementation 'com.google.android.material:material:1.5.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.3'

    // ViewModel
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.7.0'

    // Activity ViewModel
    implementation 'androidx.activity:activity-ktx:1.8.2'

    // Fragments ViewModel
    implementation 'androidx.fragment:fragment-ktx:1.6.2'

    // Dagger Hilt
    implementation "com.google.dagger:hilt-android:2.58"
    kapt "com.google.dagger:hilt-android-compiler:2.58"

    // Libreria de colores
    implementation 'com.github.yukuku:ambilwarna:2.0.1'

    // Librería de rueda de colores
    implementation 'com.github.skydoves:colorpickerview:2.2.4'
    implementation 'com.github.skydoves:colorpicker-compose:1.1.2'

    // Dependencias de Roborazzi
    androidTestImplementation("io.github.takahirom.roborazzi:roborazzi:1.44.0")
    androidTestImplementation("io.github.takahirom.roborazzi:roborazzi-compose:1.44.0")
    /*testImplementation("io.github.takahirom.roborazzi:roborazzi:1.44.0")
    testImplementation("io.github.takahirom.roborazzi:roborazzi-compose:1.44.0")*/

    // Dependencias para robolectric y compose test
    //testImplementation("org.robolectric:robolectric:4.14.1")
    androidTestImplementation("org.robolectric:robolectric:4.14.1")
    //testImplementation("androidx.compose.ui:ui-test-junit4")
    androidTestImplementation("androidx.compose.ui:ui-test-junit4")
    debugImplementation 'androidx.compose.ui:ui-test-manifest'

    //Bundle Compat
    implementation 'androidx.core:core-ktx:1.12.0'

    // Anuncios publicitarios
    //implementation 'com.google.android.gms:play-services-ads:23.0.0'

    // Zoom en la imagen
    implementation 'com.davemorrissey.labs:subsampling-scale-image-view:3.10.0'

    // Zoom con Telephoto
    implementation 'me.saket.telephoto:zoomable-image-coil:0.19.0'

    // Cargar la imagen
    implementation 'com.github.bumptech.glide:glide:4.16.0'

    // DataStore
    implementation 'androidx.datastore:datastore-preferences:1.1.1'
    //implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.7.0'

    //NavComponent
    implementation "androidx.navigation:navigation-fragment-ktx:2.9.6"
    implementation "androidx.navigation:navigation-ui-ktx:2.9.6"

    // Navegacion 3
    implementation 'androidx.navigation3:navigation3-runtime:1.1.3'
    implementation 'androidx.navigation3:navigation3-ui:1.1.3'

    // JSON
    implementation 'org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.3'

    // UnitTesting
    testImplementation 'junit:junit:4.13.2'
    // Para tests unitarios en la JVM (JUnit 4/5)
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Mockk
    testImplementation("io.mockk:mockk:1.13.12")

    // Coroutines test (unit tests)
    testImplementation 'org.jetbrains.kotlinx:kotlinx-coroutines-test:1.7.3'
    // InstantTaskExecutorRule
    testImplementation 'androidx.arch.core:core-testing:2.2.0'
    testImplementation 'net.sf.kxml:kxml2:2.3.0'

    // Robolectric
    testImplementation "org.robolectric:robolectric:4.12"

    // Opcional pero muy recomendado para testing de arquitectura:
    /*testImplementation "androidx.test:core-ktx:1.6.1"
    testImplementation "androidx.test.ext:junit-ktx:1.2.1"*/
}

kover {
    reports {
        filters {
            excludes {
                classes(
                        "*_Factory",
                        "*Factory",
                        "*_Impl",
                        "*Module*"
                )
            }
        }
    }
}